version: '3'

services:
  app:
    build: ./
    image: typescript-docker
    expose:
      - '3000'
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      BUILD: PROD
    volumes:
      - ./src:/home/app/src_live
